ParentsBank/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ParentsBank.Models;

namespace ParentsBank.Controllers
{
    [Authorize]
    public class AccountsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Accounts1
        
        public ActionResult Index()
        {
            
            if (User.IsInRole("Recipient"))
            {
                int accountid = 0;
                var account = db.Accounts
                            .Where(r => r.Recipient == User.Identity.Name);
                foreach(Account a in account)
                {
                    accountid = a.Id;
                }

                return RedirectToAction("Details", new { id = accountid });
                
            }
            else
            {
                var accounts = db.Accounts
                    .Where(a => a.Username == User.Identity.Name);
                    
                return View(accounts.ToList());
            }
        }

        public PartialViewResult transactions(int?id)
        {
            
            var tran = db.Transactions
                .Where(t => t.AccountId == id);

            return PartialView(tran.ToList());
        }

        public PartialViewResult wishlist(int? id)
        {

            var wish = db.WishLists
                .Where(w => w.AccountId == id);

            return PartialView(wish.ToList());
        }


        // GET: Accounts1/Details/5
        public ActionResult Details(int? id)
        {
            
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            if(User.IsInRole("Owner"))
            { 
            if (account.Owner != User.Identity.Name)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            }
            if (User.IsInRole("Recipient"))
            {
                if (account.Recipient != User.Identity.Name)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
            }
            CumulativeAmount(account.Id);
            return View(account);
        }

        // GET: Accounts1/Create
        [Authorize(Roles = "Owner")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Accounts1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Owner,Recipient,Name,OpenDate,InterestRate,Description")] Account account)
        {
            if (ModelState.IsValid)
            {
                int emailr = db.Accounts
                                           .Where(a => a.Recipient == account.Recipient)
                                           .Count();
                if (emailr > 0)
                {
                    ModelState.AddModelError("Recipient", "Recipient already has an account.");
                }

                int emailr1 = db.Accounts
                                           .Where(a => a.Owner == account.Recipient)
                                           .Count();
                if (emailr1 > 0)
                {
                    ModelState.AddModelError("Recipient", "Recipient is already an Owner and hence can't be a recipient.");
                }

                if(User.Identity.Name == account.Recipient)
                {
                    ModelState.AddModelError("Recipient", "Owner and Recipient Emails should be different.");
                }

                if (ModelState.IsValid)
                {
                    account.TotalAmount = 0;
                    account.Owner = User.Identity.Name;
                    account.OpenDate = DateTime.Now;
                    account.LastDeposit = Convert.ToDateTime("1/1/1900");
                   
                    account.Username = User.Identity.Name;
                    db.Accounts.Add(account);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            return View(account);
        }

        // GET: Accounts/Edit/5
        public static float tamount;
        public static float iamount;
        public static DateTime tdate;
        [Authorize(Roles = "Owner")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            if (account.Owner != User.Identity.Name)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tamount = account.TotalAmount;
            iamount = account.InterestEarned;
            tdate = account.LastDeposit;
            return View(account);
        }

        // POST: Accounts1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Owner,Recipient,Name,OpenDate,InterestRate,Description")] Account account)
        {
            if (ModelState.IsValid)
            {
                //emailcheck(account);
                //if(ModelState.IsValid)
                //{ 
                db.Entry(account).State = EntityState.Modified;
                account.Owner = User.Identity.Name;
                account.Username = User.Identity.Name;
                account.InterestEarned = iamount;
                account.TotalAmount = tamount;
                account.LastDeposit = tdate;
                db.SaveChanges();
                iamount = 0;
                tamount = 0;
                return RedirectToAction("Index");
                //}
            }
            return View(account);
        }

        // GET: Accounts1/Delete/5
        [Authorize(Roles = "Owner")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            if (account.Owner != User.Identity.Name)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(account);
        }

        // POST: Accounts1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Account acc = db.Accounts.Single(a => a.Id == id);
            if (acc.TotalAmount > 0)
            {
                //ViewBag.Error = TempData["Account has some amount and hence can't be deleted"];
                //return View();
                ModelState.AddModelError("Amount", "Account has non-zero balance and hence can't be deleted");
                return View(acc);
            }
            Account account = db.Accounts.Find(id);
            db.Accounts.Remove(account);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        /// <summary>
        /// This metohd calculate interest accumulated over a period of time in a year.
        /// This one is keeping one year interestscope here, can extend it!
        /// </summary>
        /// <param name="accountId"></param>
        public void CumulativeAmount(int accountId)
        {
            DateTime today = DateTime.Today;
            int Currentyear = today.Year;
            double interestRate = 0;
            float interestAmount = 0;
            float amount = 0;
            double Days = 0;
            double interestperTransaction = 0;


            Account accts = db.Accounts
                           .Single(ac => ac.Id == accountId);
            interestRate = (double)accts.InterestRate;


            //considering monthly compounding
            var tran = db.Transactions
                   .Where(t => t.AccountId == accountId);

            int count = tran.ToList().Count;
            List<DateTime> trDate = new List<DateTime>();
            List<float> TrAmount = new List<float>();
            List<float> interest = new List<float>();

            foreach (Transaction tr in tran)
            {
                trDate.Add(tr.TransactionDate);
                TrAmount.Add(tr.Amount);
            }
            int size = TrAmount.Count();
            for (int i = 0; i < size; i++)
            {
                if (i == (size - 1))
                {
                    Days = (today - trDate[size - 1]).Days;
                }
                else
                {
                    Days = (trDate[i + 1] - trDate[i]).Days;
                }

                amount = amount + TrAmount[i];

                interestperTransaction = (double)(amount * Math.Pow(1 + interestRate / 1200, 12 * Days / 366)) - amount;

ParentsBank/Views/Transactions/Create.cshtml
@model ParentsBank.Models.Transaction

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

         
                <div class="form-group">
            @Html.LabelFor(model => model.AccountId, "Recipient Account", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AccountId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AccountId, "", new { @class = "text-danger" })
            </div>
        </div>
        

       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
   @Html.ActionLink("Back to details", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ParentsBank/Views/Transactions/Delete.cshtml
@model ParentsBank.Models.Transaction

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.account.Recipient)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.account.Recipient)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TransactionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransactionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ParentsBank/Views/Transactions/Details.cshtml
@model ParentsBank.Models.Transaction

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.account.Recipient)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.account.Recipient)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TransactionDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransactionDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Amount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Note)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ParentsBank/Views/Transactions/Edit.cshtml
@model ParentsBank.Models.Transaction

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Transaction</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" , @readonly="readonly"} })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AccountId, "Recipient Account", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AccountId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AccountId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ParentsBank/Views/Transactions/Index.cshtml
@model IEnumerable<ParentsBank.Models.Transaction>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    <input type="button" class="btn btn-primary" title="Back to My Account" value="Back to My Account" onclick="location.href='@Url.Action("Index","Accounts")'" />
    
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.account.Recipient)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TransactionDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Amount)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Note)
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.account.Recipient)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TransactionDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Note)
        </td>
        
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>